# Generated by Django 4.2.30 on 2026-07-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_sku_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('01', 'SKU'), ('02', 'Item'), ('03', 'Vendor'), ('04', 'Customer'), ('05', 'Warehouse'), ('06', 'Purchase'), ('07', 'Sales'), ('08', 'BOM'), ('09', 'Stock'), ('10', 'Barcode')], default='01', max_length=2)),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='items.sku')),
            ],
        ),
    ]
