# Generated by Django 4.2.30 on 2026-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separator', models.CharField(default='-', max_length=5)),
                ('component_length', models.PositiveSmallIntegerField(default=3)),
                ('sequence_padding', models.PositiveSmallIntegerField(default=3)),
                ('transform', models.CharField(choices=[('alpha', 'Letters only'), ('alnum', 'Letters + digits'), ('digits', 'Digits only'), ('full', 'Keep as-is (alnum)')], default='alnum', max_length=10)),
                ('uppercase', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU format',
                'verbose_name_plural': 'SKU format',
            },
        ),
        migrations.AlterField(
            model_name='barcode',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
