# Generated by Django 4.2.30 on 2026-08-04 12:38, hand-edited to preserve data:
# Sku.item (FK) becomes Sku.items (M2M) without losing the existing links.

from django.db import migrations, models


def copy_item_to_items(apps, schema_editor):
    Sku = apps.get_model("items", "Sku")
    for sku in Sku.objects.all():
        if sku.item_id:
            sku.items.add(sku.item_id)


def copy_items_to_item(apps, schema_editor):
    Sku = apps.get_model("items", "Sku")
    for sku in Sku.objects.all():
        first = sku.items.first()
        if first:
            sku.item_id = first.pk
            sku.save(update_fields=["item"])


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_resync_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='items',
            field=models.ManyToManyField(related_name='skus', to='items.item'),
        ),
        migrations.RunPython(copy_item_to_items, copy_items_to_item),
        migrations.RemoveField(
            model_name='sku',
            name='item',
        ),
    ]
