# Generated by Django 4.2.30 on 2026-08-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_sku_items_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SKU number',
                'ordering': ('number',),
            },
        ),
        migrations.DeleteModel(
            name='SkuSequence',
        ),
    ]
