# Generated by Django 4.2.30 on 2026-08-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_skunumber_delete_skusequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='items.sku'),
        ),
    ]
