# Generated by Django 4.2.30 on 2026-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_backfill_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='source_value',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
