# Generated by Django 4.2.30 on 2026-08-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_no', models.CharField(blank=True, max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='invoicing/qr/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('company', 'Our company (seller)'), ('buyer', 'Buyer'), ('both', 'Both')], default='buyer', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('state_code', models.CharField(blank=True, max_length=4)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('seller_snapshot', models.JSONField(blank=True, default=dict)),
                ('dispatch_snapshot', models.JSONField(blank=True, default=dict)),
                ('buyer_snapshot', models.JSONField(blank=True, default=dict)),
                ('ship_to_snapshot', models.JSONField(blank=True, default=dict)),
                ('reference_no', models.CharField(blank=True, max_length=60)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, max_length=60)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=40)),
                ('payment_mode', models.CharField(blank=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('taxable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ugst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.bank')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='invoicing.enterprise')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='invoicing.enterprise')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('auto_increment', models.BooleanField(default=True)),
                ('declaration', models.TextField(blank=True, default='We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.')),
                ('terms', models.TextField(blank=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='invoicing/signature/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoicing/logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice master',
                'verbose_name_plural': 'Invoice master',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('hsn', models.CharField(blank=True, max_length=20)),
                ('scanned_code', models.CharField(blank=True, db_index=True, max_length=128)),
                ('sku_code', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
